### ISSUE TITLE
Fix File Links Under Data 

### ISSUE THREAD

**Issue by cconrad8** [gf-dcc/portal#48]
File links available under [Data](https://gf-dcc.github.io/info-website/data) are dead. It brings you to https://www.synapse.org/#!Synapse:undefined.

**Comment by anngvu** [comment]
Note: also remove the modal for Seven Bridges

**Comment by cconrad8** [comment]
This is also true for filenames under files

**Comment by cconrad8** [comment]
@inodb can this be prioritized next please?

**Comment by cconrad8** [comment]
Hi @onursumer would you be able to work on the link issues? Thanks!

**Comment by onursumer** [comment]
This is happening because GF data model is different than HTAN data model. `FileTable` expects all files to have a valid `synapseId` field and uses that value to generate the links:

https://github.com/gf-dcc/portal/blob/5943f961e59eab45bd1c4f15c24d464cd27c3257/components/FileTable.tsx#L319

However, files defined in the GF data model don't have a `synapseId` field. Here is an example:

```
"files" : [ {
    "atlas_id" : "syn51755921",
    "biospecimenIds" : [ "NA_Biospecimen" ],
    "DataFileID" : "syn34064609",
    "dataset_id" : "syn27337139",
    "fileFormat" : "NA",
    "Component" : "NA",
    "diagnosisIds" : [ "NA_Participant" ],
    "level" : "",
    "filename" : "SVC003373_mergecg.bed.gz",
    "dataset_name" : "WGBS_Level_2",
    "assayName" : "",
    "projectId" : "syn25813057",
    "demographicsIds" : [ "NA_Participant" ]
  }, {
  ...
  }
```

As a result we end up getting `undefined` for all the synapse links. A quick fix would be to modify the code and refer to another field, probably `DataFieldID` is what we need in this case. (I can't verify this because I don't have access to https://www.synapse.org/#!Synapse:syn34064609)

However, ideally, we should transform the GF data model to the HTAN data model if possible, and directly use the existing components with minimal modification. The more these two data models deviate from each other, the harder it gets to maintain reusability of existing HTAN codebase.

**Comment by cconrad8** [comment]
Thanks @onursumer for the info. I just made a fix to change the DataFileID to synapseId. I tagged you in the PR if you can review. Thanks!
